class ApplicationController:
    def __init__(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def join(self) -> None: ...
    def set_ass_input(self, content: str) -> None: ...
    def set_paused(self, paused: bool) -> None: ...
    def set_start_time(self, ms: int) -> None: ...
    def get_start_time(self) -> int: ...
    def set_hidden(self, hidden: bool) -> None: ...
    def set_locked(self, locked: bool) -> None: ...
    def get_status(self) -> dict: ...
